# **NUMPY EXPLORATION**

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'2.0.2'

# Array Dimensions

In [3]:
# 0 - Dimensional Array ()

arr = np.array(42)
arr

array(42)

In [4]:
# 1 - Dimensional Array ([])

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
# 2 - Dimensional Array ([[]])

arr = np.array([[1,2,3] , [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 3 - Dimensional Array ([[[]]])

arr = np.array([[[1,2],[3,4]] , [[1,2],[3,4]]])
arr

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [7]:
# Array Dimension

arr = np.array([1,2,3,4,5])
arr.ndim

1

In [8]:
# Change the Array Dimesnion

arr = np.array([1,2,3,4,5] , ndmin = 4)
arr

array([[[[1, 2, 3, 4, 5]]]])

# Array Slicing by Index

In [9]:
# 1-D Array Slicing by Index
# [Start, Stop, Step]

arr = np.array([1,2,3,4,5])

print(arr[0])           # Index 0 refers to first element
print(arr[1:4])         # Index 1 inclued but Index 4 not included
print(arr[:3])          # Starting to Index 2 but Index 3 not included
print(arr[2:])          # Index 2 to End
print(arr[:])           # Selects all
print(arr[::2])         # Step wise
print(arr[1:4:2])       # Index 1 to Index 3 in step of 2 but index 4 not included

1
[2 3 4]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[1 3 5]
[2 4]


In [10]:
# Array Slicing by negative Index

arr = np.array([1,2,3,4,5])

print(arr[-1])           # Index -1 refers to last element
print(arr[-4:-1])        # Index -4 inclued but Index -1 not included
print(arr[:-3])          # Starting to Index -4 but Index -3 not included
print(arr[-2:])          # Index -2 to End 

5
[2 3 4]
[1 2]
[4 5]


In [11]:
# 3-D Array Slicing by Index
# [Depth, Row, Element]

arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6]],

                [[ 7,  8,  9],
                 [10, 11, 12]]])
                 
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr[0,1]

array([4, 5, 6])

In [14]:
arr[0,1,2]

np.int64(6)

In [15]:
arr[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr[:,:,2]

array([[ 3,  6],
       [ 9, 12]])

In [17]:
arr[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [18]:
arr[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [19]:
arr[:,1:2,1:3]

array([[[ 5,  6]],

       [[11, 12]]])

# Data Types and Type Conversion

In [20]:
# Datatypes using "dtype" and Type of Array

arr = np.array([1,2,3,4,5])

print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [21]:
# Type conversion to "float"

arr = np.array([1,2,3,4,5], dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [22]:
# Type conversion to "int"

arr = np.array([1.3, 2.9, 3.0, 4.6, 5.1], dtype=int)
arr

array([1, 2, 3, 4, 5])

In [23]:
# Type conversion to "str"

arr = np.array([1,2,3,4,5], dtype=str)
arr

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [24]:
# Type conversion using "astype" method

arr = np.array([1.3, 2.9, 3.0, 4.6, 5.1])
new_arr = arr.astype(int)
new_arr

array([1, 2, 3, 4, 5])

Copy vs View

In [25]:
# "copy()" will not affect the original array - Owns the data

arr = np.array([1,2,3,4,5])

x = arr.copy()
x

array([1, 2, 3, 4, 5])

In [26]:
# "view()" will affect the original array - Doesn't own the data

arr = np.array([1,2,3,4,5])

y = arr.view()
y

array([1, 2, 3, 4, 5])

In [27]:
# "base" will check owns the data or not

print(x.base)           # Owns the data
print(y.base)           # Doesn't own the data

None
[1 2 3 4 5]


# Zeros Array

In [28]:
# 1 - D Zeros Array ()

zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [29]:
# 2 - D Zeros Array (())

zeros_arr = np.zeros((5,5))
zeros_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
# 3 - D Zeros Array (())

zeros_arr = np.zeros((2,5,5))
zeros_arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# Ones Array

In [31]:
# 1 - D Ones Array ()

ones_arr = np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [32]:
# 2 - D Ones Array ()

ones_arr = np.ones((5,5))
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# 3 - D Ones Array ()

ones_arr = np.ones((2,5,5))
ones_arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Create Arrays

In [ ]:
# Arange the array (Start, Stop)

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Arange the array in steps (Start, Stop, Step)

arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [36]:
# Linespace array in parts (Start, Stop, Space)

arr = np.linspace(0,1,6)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# Divide into 50 equal parts, if no linespace given

arr = np.linspace(0,1)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

# Array Shape and Re-Shape

In [38]:
# Shape of Array

arr = np.arange(1,13)
arr.shape

(12,)

In [39]:
# Re-Shaping the 1-D array to 2-D array

arr = np.arange(1,13)
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
# Re-Shaping the 1-D array to 3-D array

arr = np.arange(1,13)
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
# If 3rd dimension is unknown, pass -1

arr = np.arange(1,13)
arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Joining Arrays

Concatenate

In [42]:
# Concatenate 1-D Array
# Use either concat or concatenate, both are acceptable

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.concat((arr_1,arr_2))
np.concatenate((arr_1,arr_2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# Concatenate 2-D Arrays

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.concat((arr_1,arr_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [44]:
# Concatenate 2-D Arrays over the columns (axis=1)

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.concat((arr_1,arr_2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Stack

In [45]:
# Stacking 1-D Array

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.stack((arr_1,arr_2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Stacking 2-D Arrays over the columns (axis=1)

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.stack((arr_1,arr_2), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [47]:
# Horizontal Stacking (hstack) - Along rows

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.hstack((arr_1,arr_2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
# Vertical Stacking (vstack) - Along columns

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.vstack((arr_1,arr_2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# Depth Stacking (dstack) - Along Depth

arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

np.dstack((arr_1,arr_2))

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [50]:
# Stacking 2-D Arrays

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.stack((arr_1,arr_2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
# 2-D Horizontal Stacking (hstack) - Along rows

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.hstack((arr_1,arr_2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
# 2-D Vertical Stacking (vstack) - Along columns

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.vstack((arr_1,arr_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
# 2-D Depth Stacking (dstack) - Along Depth

arr_1 = np.array([[1,2] , [3,4]])
arr_2 = np.array([[5,6] , [7,8]])

np.dstack((arr_1,arr_2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

# Splitting Arrays

In [54]:
# Array Splitting
# Use either array_split or split, both are acceptable

arr = np.array([1,2,3,4,5,6])

np.array_split(arr,3)
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [55]:
# If splitting is not given in proper ratio, it will split accordingly

arr = np.array([1,2,3,4,5,6])

np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Array Search and Sort

In [56]:
# "where" function returns the index of value

arr = np.array([1,2,4,7,4,5,8,0,6,4,9])

np.where(arr == 4)

(array([2, 4, 9]),)

In [57]:
# "searchsorted" function will direct the index of value to be inserted

arr = np.array([1,2,4,7,4,5,8,0,6,4,9])

np.searchsorted(arr,3)

np.int64(2)

In [58]:
# "sort" function will sort in ascending order

arr = np.array([1,2,4,7,4,5,8,0,6,4,9])

np.sort(arr)

array([0, 1, 2, 4, 4, 4, 5, 6, 7, 8, 9])

# Random Arrays

Float - rand()

In [59]:
# Array gives the random value between (0,1)
# 0-D Array

arr = np.random.rand()
arr

0.12983903562811694

In [60]:
# 1-D Array

arr = np.random.rand(3)
arr

array([0.40482966, 0.07664413, 0.21259655])

In [61]:
# 2-D Array

arr = np.random.rand(5,3)
arr

array([[0.96283339, 0.90982231, 0.38162086],
       [0.30169751, 0.86268496, 0.63036442],
       [0.93602812, 0.19324821, 0.72317025],
       [0.85842637, 0.7963793 , 0.71289525],
       [0.59584214, 0.20088943, 0.42983451]])

In [62]:
# 3-D Array

arr = np.random.rand(2,4,3)
arr

array([[[0.36886845, 0.65600477, 0.65393726],
        [0.23849678, 0.78621606, 0.34908165],
        [0.72168321, 0.8760447 , 0.78435863],
        [0.39066237, 0.04605029, 0.90268918]],

       [[0.16990896, 0.94314643, 0.01880671],
        [0.02535694, 0.5327455 , 0.67217741],
        [0.50965886, 0.2611169 , 0.47060608],
        [0.28288193, 0.74245936, 0.34719712]]])

Integer - randint()

In [63]:
# Array that gives the random integer value within 100
# 0-D Array

arr = np.random.randint(100)
arr

10

In [64]:
# 1-D Array of size = 5

arr = np.random.randint(100, size=5)
arr

array([43, 14, 23, 81, 32], dtype=int32)

In [65]:
# 2-D Array of given size

arr = np.random.randint(100, size=(4,5))
arr

array([[65, 87, 60, 79, 26],
       [80, 47, 92,  4, 20],
       [34, 53, 56, 92, 17],
       [89, 52, 10, 76, 54]], dtype=int32)

In [66]:
# 3-D Array of given size

arr = np.random.randint(100, size=(2,3,5))
arr

array([[[62, 68, 66, 44, 38],
        [25,  0, 56, 62, 33],
        [22, 15, 10, 87,  0]],

       [[42,  3, 19, 33, 55],
        [89, 90, 58, 29, 27],
        [13, 28, 52, 98, 14]]], dtype=int32)

Random Choice

In [67]:
# Array random choice within the range

arr = np.arange(1,10)
np.random.choice(arr, size=(3,4))

array([[5, 2, 5, 1],
       [7, 4, 3, 8],
       [8, 8, 4, 3]])

In [68]:
arr = np.random.choice([1,2,3,4], size=(3,4))
arr

array([[4, 3, 1, 3],
       [1, 4, 4, 4],
       [4, 1, 3, 3]])

In [69]:
# Data distribution using the probabliity

arr = np.random.choice([1,2,3,4], p=[0.2,0.4,0.3,0.1], size=(100))
arr

array([2, 3, 4, 2, 3, 1, 2, 1, 1, 3, 3, 2, 1, 2, 3, 1, 1, 2, 3, 2, 1, 3,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 1, 3, 2, 1, 3, 4, 4, 3, 3, 2, 2,
       3, 1, 2, 4, 2, 2, 4, 3, 2, 2, 2, 4, 3, 2, 3, 1, 1, 3, 2, 4, 2, 3,
       2, 2, 3, 1, 3, 1, 2, 2, 2, 3, 2, 4, 3, 1, 2, 3, 3, 2, 2, 1, 2, 3,
       2, 2, 3, 2, 1, 1, 4, 4, 3, 3, 3, 4])

In [70]:
arr = np.random.choice([1,2,3,4], p=[0.2,0.4,0.3,0.1], size=(5,20))
arr

array([[2, 3, 3, 1, 2, 2, 2, 2, 2, 3, 2, 2, 4, 3, 3, 2, 3, 2, 2, 3],
       [4, 2, 4, 3, 3, 3, 3, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 4, 2],
       [4, 2, 3, 2, 1, 3, 2, 3, 2, 3, 2, 2, 1, 1, 2, 2, 2, 1, 2, 3],
       [1, 2, 3, 3, 2, 2, 2, 2, 2, 3, 4, 2, 1, 2, 4, 2, 3, 1, 2, 1],
       [2, 1, 4, 2, 2, 3, 2, 2, 3, 2, 4, 3, 1, 2, 2, 2, 2, 2, 3, 1]])

Random Normal

In [71]:
# Random value in range of 1000

arr = np.random.normal(1000)
arr

1000.4726237372942

In [72]:
# 1-D Normal array of size 10

arr = np.random.normal(size=(10))
arr

array([ 0.48411529,  0.00973576,  0.15558892, -0.43161453, -0.4355242 ,
       -0.57669505, -1.77260006,  1.24504731, -1.75511536,  0.32347815])

In [73]:
# 2-D Normal array of size (2,3)

arr = np.random.normal(size=(2,3))
arr

array([[ 2.43576971, -0.53386056,  2.09171092],
       [-0.39018651,  0.398514  ,  2.15361221]])

In [74]:
# 2-D Normal array with mean= 5, SD= 2, size= (3,2)

arr = np.random.normal(loc=5, scale=2, size=(3, 2))
arr

array([[6.40960628, 5.02566854],
       [2.64004319, 4.18497935],
       [7.07227067, 7.33784954]])

Shuffle and Permutation

In [75]:
# Shuffle will change the original array

arr = np.array([1,2,3,4,5])

np.random.shuffle(arr)

In [76]:
# Permutation will keep the original array same

arr = np.array([1,2,3,4,5])

np.random.permutation(arr)

array([5, 3, 1, 2, 4])

# Mathematical Operations

Arithmatic Operations

In [77]:
# Operations on elements of an array

arr = np.array([1,2,3,4,5])

print(arr[0] + arr[1])         # Addition
print(arr[4] - arr[2])         # Subtraction
print(arr[1] * arr[3])         # Multiplication
print(arr[3] / arr[1])         # Division
print(arr[4] // arr[1])        # Floor (Return the integer)
print(arr[4] % arr[2])         # Modulus

3
2
8
2.0
2
2


In [78]:
# Operations on multiple arrays 

arr_1 = np.array([9,6,8,7])
arr_2 = np.array([4,1,2,3])

print(arr_1 + arr_2)        # Addition
print(arr_1 - arr_2)        # Subtraction
print(arr_1 * arr_2)        # Multiplication
print(arr_1 / arr_2)        # Division
print(arr_1 % arr_2)        # Modulus

[13  7 10 10]
[5 5 6 4]
[36  6 16 21]
[2.25       6.         4.         2.33333333]
[1 0 0 1]


In [79]:
# Operations on multiple arrays using functions

arr_1 = np.array([9,6,8,7])
arr_2 = np.array([4,1,2,3])

print(np.add(arr_1, arr_2))             # Addition
print(np.subtract(arr_1, arr_2))        # Subtraction
print(np.multiply(arr_1, arr_2))        # Multiplication
print(np.divide(arr_1, arr_2))          # Division
print(np.mod(arr_1, arr_2))             # Modulus
print(np.divmod(arr_1, arr_2))          # Divmod - Return Quotient and Modulus
print(np.absolute(arr_1))               # Absolute - Retun Positive values
print(np.pow(arr_1, arr_2))             # Power

[13  7 10 10]
[5 5 6 4]
[36  6 16 21]
[2.25       6.         4.         2.33333333]
[1 0 0 1]
(array([2, 6, 4, 2]), array([1, 0, 0, 1]))
[9 6 8 7]
[6561    6   64  343]


In [80]:
# Summation and Product of all elements

arr_1 = np.array([9,6,8,7])
arr_2 = np.array([4,1,2,3])

print(np.sum([arr_1,arr_2]))        # Summation
print(np.prod([arr_1,arr_2]))       # Product

40
72576


In [81]:
# Summation and Product of all elements along the column (axis=1)

arr_1 = np.array([9,6,8,7])
arr_2 = np.array([4,1,2,3])

print(np.sum([arr_1,arr_2], axis=1))        # Summation
print(np.prod([arr_1,arr_2], axis=1))       # Product

[30 10]
[3024   24]


Rounding off Decimals

In [82]:
# "trunc()" - Return the integer

arr = np.trunc([3.667, -3.166])
arr

array([ 3., -3.])

In [83]:
# "fix()" - Return the integer

arr = np.fix([3.667, -3.166])
arr

array([ 3., -3.])

In [84]:
# "arond()" - Round off to given decimal

arr = np.around(3.667, 2)
arr

np.float64(3.67)

In [85]:
# "floor()" - Return the nearest lower integer

arr = np.floor([3.667, -3.166])
arr

array([ 3., -4.])

In [86]:
# "ceil()" - Return the nearest higher integer

arr = np.ceil([3.667, -3.166])
arr

array([ 4., -3.])

Logarithamic Function

In [87]:
# Log operation of base e

arr = np.arange(1,10)

np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [88]:
# Log operation of base 2

arr = np.arange(1,10)

np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [89]:
# Log operation of base 10

arr = np.arange(1,10)

np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

LCM and GCD

In [90]:
# LCM and GCD of numbers

print(np.lcm(4, 6))
print(np.gcd(4, 6))

12
2


In [91]:
# LCM and GCD of Arrays

arr = np.array([4,6,8])

print(np.lcm.reduce(arr))
print(np.gcd.reduce(arr))


24
2


In [92]:
# Program to reverse the list

lis = [1,2,3,4,5,6,7,8,9]
length = len(lis)
print(lis)
for i in range(length //2):
    a = lis[i]
    lis[i] = lis[length-i-1]
    lis[length-i-1] = a
print(lis)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
